version: '3.8'

services:
  backend:
    build: .
    container_name: sdr-backend
    restart: unless-stopped
    ports:
      - "80:3001" # Mapeia a porta 80 do servidor para a 3001 do Node
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules